package command

import (
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/ForceCLI/force/config"
	. "github.com/ForceCLI/force/error"
	. "github.com/ForceCLI/force/lib"
)

var cmdExport = &Command{
	Run:   runExport,
	Usage: "export [options] [dir]",
	Short: "Export metadata to a local directory",
	Long: `
Export metadata to a local directory

Export Options
  -w, -warnings  # Display warnings about metadata that cannot be retrieved
  -x, -exclude   # Exclude given metadata type
  -i, -include   # Include given metadata type
  -p, -package   # Include managed package metadata
  -n, -newline   # Add newline for output

Examples:

  force export

  force export org/schema

  force export -x ApexClass -x CustomObject
`,
	MaxExpectedArgs: 1,
}

type metadataList []string

func (i *metadataList) String() string {
	return fmt.Sprint(*i)
}

func (i *metadataList) Set(value string) error {
	*i = append(*i, value)
	return nil
}

var (
	showWarnings           bool
	includeManagedPackages bool
	excludeMetadataNames   metadataList
	includeMetadataNames   metadataList
	addNewline             bool
)

func init() {
	cmdExport.Flag.BoolVar(&showWarnings, "w", false, "show warnings")
	cmdExport.Flag.BoolVar(&showWarnings, "warnings", false, "show warnings")
	cmdExport.Flag.Var(&excludeMetadataNames, "x", "exclude metadata type")
	cmdExport.Flag.Var(&excludeMetadataNames, "exclude", "exclude metadata type")
	cmdExport.Flag.Var(&includeMetadataNames, "i", "include only metadata type")
	cmdExport.Flag.Var(&includeMetadataNames, "include", "include only metadata type")
	cmdExport.Flag.BoolVar(&includeManagedPackages, "p", false, "include managed packages")
	cmdExport.Flag.BoolVar(&includeManagedPackages, "package", false, "include managed packages")
	cmdExport.Flag.BoolVar(&addNewline, "n", false, "add newline")
	cmdExport.Flag.BoolVar(&addNewline, "newline", false, "add newline")
}

func runExport(cmd *Command, args []string) {
	// Get path from args if available
	var err error
	var root string
	if len(args) == 1 {
		root, err = filepath.Abs(args[0])
	}
	if err != nil {
		fmt.Printf("Error obtaining file path\n")
		ErrorAndExit(err.Error())
	}
	force, _ := ActiveForce()
	sobjects, err := force.ListSobjects()
	if err != nil {
		ErrorAndExit(err.Error())
	}
	query := make(ForceMetadataQuery, 0)
	customObject := "CustomObject"
	standardValueSet := "StandardValueSet"

	sort.Strings(excludeMetadataNames)
	sort.Strings(includeMetadataNames)

	exportAll := true
	if len(includeMetadataNames) > 0 {
		exportAll = false
	}

	if (!isExcluded(customObject) && exportAll) || isIncluded(customObject) {
		stdObjects := make([]string, 1, len(sobjects)+1)
		stdObjects[0] = "*"
		for _, sobject := range sobjects {
			name := sobject["name"].(string)
			include := true
			if strings.Count(name, "__") > 1 {
				if !includeManagedPackages {
					include = false
				}
			}
			if include && !strings.HasSuffix(name, "Tag") && !strings.HasSuffix(name, "History") &&
				!strings.HasSuffix(name, "Share") && !strings.HasSuffix(name, "ChangeEvent") &&
				!strings.HasSuffix(name, "Feed") {
				stdObjects = append(stdObjects, name)
			}
		}
		stdObjects = append(stdObjects, "Activity")
		stdObjects = append(stdObjects, "PersonAccount")

		query = append(query, ForceMetadataQueryElement{Name: []string{customObject}, Members: stdObjects})
	}

	standardValueSetNames := []string{
		"AAccreditationRating",
		"AccountContactMultiRoles",
		"AccountContactRole",
		"AccountOwnership",
		"AccountRating",
		"AccountType",
		"AccreditationAccreditingBody",
		"AccreditationStatus",
		"AccreditationSubType",
		"AccreditationType",
		"ACInitSumEmployeeType",
		"ACInitSumInitiativeType",
		"ACISumRecipientCategory",
		"ACorruptionInitSumCountry",
		"ACorruptionInitSumRegion",
		"ActivityTimeEnum",
		"AdmissionSource",
		"AdmissionType",
		"AllergyIntoleranceCategory",
		"AllergyIntoleranceSeverity",
		"AllergyIntoleranceStatus",
		"AllergyIntoleranceType",
		"AllergyVerificationStatus",
		"AppealRequestReasonType",
		"ApprovedLevelOfCare",
		"AQuestionQuestionCategory",
		"AReasonAppointmentReason",
		"AssessmentRating",
		"AssessmentStatus",
		"AssetActionCategory",
		"AssetRelationshipType",
		"AssetStatus",
		"AssociatedLocationType",
		"AuthorNoteRecipientType",
		"BarrierCodeType",
		"BCCertificationType",
		"BLicenseJurisdictionType",
		"BLicenseVerificationStatus",
		"BoardCertificationStatus",
		"BusinessLicenseStatus",
		"CampaignMemberStatus",
		"CampaignStatus",
		"CampaignType",
		"CardType",
		"CareAmbulanceTransReason",
		"CareAmbulanceTransType",
		"CareBarrierPriority",
		"CareBarrierStatus",
		"CareBenefitVerifyRequestStatus",
		"CareDeterminantPriority",
		"CareDeterminantTypeDomain",
		"CareDeterminantTypeType",
		"CareEpisodeStatus",
		"CareEpisodeType",
		"CareItemStatus",
		"CareItemStatusReason",
		"CareMetricTargetType",
		"CareObservationCategory",
		"CareObservationStatus",
		"CarePlanActivityStatus",
		"CarePlanAuthorizationType",
		"CarePlanDetailDetailType",
		"CarePreauthItemLaterality",
		"CarePreauthStatus",
		"CareProgramEnrolleeStatus",
		"CareProgramGoalPriority",
		"CareProgramGoalStatus",
		"CareProgramProductStatus",
		"CareProgramProviderRole",
		"CareProgramProviderStatus",
		"CareProgramStatus",
		"CareProgramTeamMemberRole",
		"CareQuantityType",
		"CareRegisteredDeviceStatus",
		"CareRequestExtensionAmbulanceTransportReason",
		"CareRequestExtensionAmbulanceTransportType",
		"CareRequestExtensionNursingHomeResidentialStatus",
		"CareRequestExtensionRequestType",
		"CareRequestExtensionServiceLevel",
		"CareRequestMemberGender",
		"CareRequestMemberPrognosis",
		"CareRequestQuantityType",
		"CareRequestReviewerStatus",
		"CareSpecialtySpecialtyType",
		"CareSpecialtySpecialtyUsage",
		"CareTaxonomyTaxonomyType",
		"CareTeamStatus",
		"CaseContactRole",
		"CaseOrigin",
		"CasePriority",
		"CaseReason",
		"CaseServicePlanStatus",
		"CaseStatus",
		"CaseType",
		"CBCoverageType",
		"CBenefitItemLimitTermType",
		"CBItemLimitCoverageLevel",
		"CBItemLimitNetworkType",
		"CCFALineOfBusiness",
		"CCPAdditionalBenefits",
		"CCProjectMitigationType",
		"CCPStandardsAgencyName",
		"CCreditProjectProjectType",
		"CDPresentOnAdmission",
		"CEIdentifierIdUsageType",
		"CEncounterAdmissionSource",
		"CEncounterCategory",
		"CEncounterDietPreference",
		"CEncounterFacilityStatus",
		"CEncounterServiceType",
		"CEncounterSpecialCourtesy",
		"CEncounterStatus",
		"CEpisodeDetailDetailType",
		"ChangeRequestRelatedItemImpactLevel",
		"ChangeRequestBusinessReason",
		"ChangeRequestCategory",
		"ChangeRequestImpact",
		"ChangeRequestPriority",
		"ChangeRequestRiskLevel",
		"ChangeRequestStatus",
		"ClassRankReportingFormat",
		"ClassRankWeightingType",
		"ClinicalAlertCategories",
		"ClinicalAlertStatus",
		"ClinicalCaseType",
		"ClinicalDetectedIssueSeverityLevel",
		"ClinicalDetectedIssueStatus",
		"COComponentValueType",
		"COCValueInterpretation",
		"CodeSetCodeSetType",
		"CommunicationChannel",
		"CompanyRelationshipType",
		"ConsequenceOfFailure",
		"ContactPointAddressType",
		"ContactPointUsageType",
		"ContactRequestReason",
		"ContactRequestStatus",
		"ContactRole",
		"ContractContactRole",
		"ContractLineItemStatus",
		"ContractStatus",
		"COProcessingResult",
		"COValueInterpretation",
		"CPAActivityType",
		"CPADetailDetailType",
		"CPADetailDetailType",
		"CPAdverseActionActionType",
		"CPAdverseActionStatus",
		"CPAgreementAgreementType",
		"CPAgreementLineofBusiness",
		"CPAProhibitedActivity",
		"CPDProblemPriority",
		"CPEligibilityRuleStatus",
		"CPEnrolleeProductStatus",
		"CPEnrollmentCardStatus",
		"CPFSpecialtySpecialtyRole",
		"CProgramProductAvailability",
		"CPTemplateProblemPriority",
		"CRDDrugAdministrationSetting",
		"CRDNameType",
		"CCRDPriority",
		"CCRDPriority",
		"CRDRequestType",
		"CRDStatus",
		"CRDStatusReason",
		"CRECaseSubStatus",
		"CRECaseSubStatus",
		"CREDocumentAttachmentStatus",
		"CREIndependentReviewDetermination",
		"CREPriorAuthRequestIdentifier",
		"CREPriorDischargeStatus",
		"CREReopenRequestOutcome",
		"CREReopenRequestType",
		"CRERequestOutcome",
		"CRIApprovedLevelOfCare",
		"CRIClinicalDetermination",
		"CRICurrentLevelOfCare",
		"CRIDeniedLevelOfCare",
		"CRIModifiedLevelOfCare",
		"CRIPriority",
		"CRIRequestedLevelOfCare",
		"CRIRequestType",
		"CRReviewerReviewerType",
		"CSBundleUsageType",
		"CServiceRequestIntent",
		"CServiceRequestPriority",
		"CServiceRequestStatus",
		"CSRequestDetailDetailType",
		"CurrentLevelOfCare",
		"DChecklistItemStatus",
		"DecisionReason",
		"DeniedLevelOfCare",
		"DiagnosisCodeType",
		"DiagnosticSummaryCategory",
		"DiagnosticSummaryStatus",
		"DigitalAssetStatus",
		"DEInclSumDiversityType",
		"DEInclSumEmployeeType",
		"DEInclSumEmploymentType",
		"DEInclSumGender",
		"DEISumDiversityCategory",
		"DischargeDiagnosisCodeType",
		"DIssueDetailType",
		"DivrsEquityInclSumLocation",
		"DivrsEquityInclSumRace",
		"DrugClinicalDetermination",
		"DSDDocumentRelationType",
		"DSDocumentStage",
		"DSummaryDetailDetailType",
		"DSummaryUsageType",
		"ECTypeContactPointType",
		"EducationLevel",
		"EEligibilityCriteriaStatus",
		"EmploymentOccupation",
		"EmploymentStatus",
		"EngagementAttendeeRole",
		"EngagementSentimentEnum",
		"EngagementStatusEnum",
		"EngagementTypeEnum",
		"EnrolleeOptOutReasonType",
		"EntitlementType",
		"EBSEmployeeBenefitType",
		"EBSPercentageCalcType",
		"EBSummaryBenefitUsage",
		"EBSummaryEmploymentType",
		"EBSEmployeeBenefitType",
		"EBSPercentageCalcType",
		"EDemographicSumAgeGroup",
		"EDemographicSumGender",
		"EDemographicSumRegion",
		"EDemographicSumReportType",
		"EDemographicSumWorkType",
		"EDevelopmentSumGender",
		"EDSumEmployeeType",
		"EDSumEmploymentType",
		"EDSumProgramCategory",
		"EPSumMarket",
		"EPSumPerformanceCategory",
		"EPSumPerformanceType",
		"EPSumRegion",
		"ERCompanyBusinessRegion",
		"ERCompanySector",
		"EReductionTargetTargetType",
		"ERTargetOtherTargetKpi",
		"ERTTargetSettingMethod",
		"EventSubject",
		"EventType",
		"FacilityRoomBedType",
		"FinalLevelOfCare",
		"FinanceEventAction",
		"FinanceEventType",
		"FiscalYearPeriodName",
		"FiscalYearPeriodPrefix",
		"FiscalYearQuarterName",
		"FiscalYearQuarterPrefix",
		"ForecastingItemCategory",
		"FreightHaulingMode",
		"FtprntAuditApprovalStatus",
		"FulfillmentStatus",
		"FulfillmentType",
		"GADetailDetailType",
		"GoalAssignmentProgressionStatus",
		"GoalAssignmentStatus",
		"GoalDefinitionCategory",
		"GoalDefinitionUsageType",
		"GovtFinancialAsstSumType",
		"GpaWeightingType",
		"GrievanceType",
		"HCFacilityLocationType",
		"HcpCategory",
		"HcpCodeType",
		"HealthCareDiagnosisCategory",
		"HealthCareDiagnosisCodeType",
		"HealthCareDiagnosisGender",
		"HealthcareProviderStatus",
		"HealthConditionDetailType",
		"HealthConditionSeverity",
		"HealthConditionStatus",
		"HealthConditionType",
		"HealthDiagnosticStatus",
		"HFNetworkGenderRestriction",
		"HFNetworkPanelStatus",
		"HPayerNetworkNetworkType",
		"HPayerNwkLineOfBusiness",
		"HPFGenderRestriction",
		"HPFTerminationReason",
		"HProviderNpiNpiType",
		"HProviderProviderClass",
		"HProviderProviderType",
		"HPSpecialtySpecialtyRole",
		"HSActionLogActionStatus",
		"IaApplnStatus",
		"IaAuthCategory",
		"IaInternalStatus",
		"IAItemStatus",
		"IARejectionReason",
		"IAServiceType",
		"IdeaCategory",
		"IdeaMultiCategory",
		"IdeaStatus",
		"IdeaThemeStatus",
		"IdentifierIdUsageType",
		"IFnolChannel",
		"IncidentCategory",
		"IncidentImpact",
		"IncidentPriority",
		"IncidentRelatedItemImpactLevel",
		"IncidentRelatedItemImpactType",
		"IncidentReportedMethod",
		"IncidentStatus",
		"IncidentSubCategory",
		"IncidentType",
		"IncidentUrgency",
		"Industry",
		"InterventionCodeType",
		"IPCancelationReasonType",
		"IPCBenefitPaymentFrequency",
		"IPCCategory",
		"IPCCategoryGroup",
		"IPCDeathBenefitOptionType",
		"IPCIncomeOptionType",
		"IPCLimitRange",
		"IPolicyAuditTerm",
		"IPolicyChangeSubType",
		"IPolicyChangeType",
		"IPolicyChannel",
		"IPolicyPlanTier",
		"IPolicyPlanType",
		"IPolicyPolicyType",
		"IPolicyPremiumCalcMethod",
		"IPolicyPremiumFrequency",
		"IPolicyPremiumPaymentType",
		"IPolicyStatus",
		"IPolicySubStatusCode",
		"IPolicyTerm",
		"IPolicyTransactionStatus",
		"IPolicyTransactionType",
		"IPOwnerPOwnerType",
		"IPParticipantRole",
		"IPPRelationshipToInsured",
		"LeadSource",
		"LeadStatus",
		"LicenseClassType",
		"LineOfAuthorityType",
		"LocationType",
		"LPIApplnCategory",
		"LPIApplnStatus",
		"MedicationCategoryEnum",
		"MedicationDispenseMedAdministrationSettingCategory",
		"MedicationDispenseStatus",
		"MedicationDispenseSubstitutionReason",
		"MedicationDispenseSubstitutionType",
		"MedicationStatementStatus",
		"MedicationStatus",
		"MedReviewRepresentativeType",
		"MedTherapyReviewSubtype",
		"MemberPlanPrimarySecondaryTertiary",
		"MemberPlanRelToSub",
		"MemberPlanStatus",
		"MemberPlanVerificStatus",
		"MilitaryService",
		"ModifiedCareCodeType",
		"ModifiedDiagnosisCodeType",
		"ModifiedDrugCodeType",
		"ModifiedLevelOfCare",
		"MRequestPriority",
		"MRequestStatus",
		"MRequestTherapyDuration",
		"MRequestType",
		"MStatementDeliverySetting",
		"MStatementDetailType",
		"OcrService",
		"OcrStatus",
		"OIncidentSummaryHazardType",
		"OISCorrectiveActionType",
		"OISummaryIncidentSubtype",
		"OISummaryIncidentType",
		"OISummaryPenaltyType",
		"OpportunityCompetitor",
		"OpportunityStage",
		"OpportunityType",
		"OrderItemSummaryChgRsn",
		"OrderStatus",
		"OrderSummaryRoutingSchdRsn",
		"OrderSummaryStatus",
		"OrderType",
		"ParProvider",
		"PartnerRole",
		"PartyProfileCountryofBirth",
		"PartyProfileEmploymentType",
		"PartyProfileFundSource",
		"PartyProfileGender",
		"PartyProfileResidentType",
		"PartyProfileReviewDecision",
		"PartyProfileRiskType",
		"PartyProfileStage",
		"PartyScreeningStepType",
		"PartyScreeningSummaryStatus",
		"PatientImmunizationStatus",
		"PEFEFctrDataSourceType",
		"PersonEmploymentType",
		"PersonLanguageLanguage",
		"PersonLanguageSpeakingProficiencyLevel",
		"PersonLanguageWritingProficiencyLevel",
		"PersonNameNameUsageType",
		"PersonVerificationStatus",
		"PHealthReactionSeverity",
		"PIdentityVerificationResult",
		"PIdentityVerificationStatus",
		"PIVerificationStepStatus",
		"PIVerificationStepType",
		"PIVerificationVerifiedBy",
		"PIVOverriddenResult",
		"PIVResultOverrideReason",
		"PIVSVerificationDecision",
		"PlaceOfService",
		"PlanBenefitStatus",
		"PMDDosageDefinitionType",
		"PMDosageDosageAmountType",
		"PMDosageRateType",
		"PMPDetailDetailType",
		"PMPOutcome",
		"PMPStatus",
		"PPCreditScoreProvider",
		"PPPrimaryIdentifierType",
		"PProfileAddressAddressType",
		"PProfileCountryOfDomicile",
		"PProfileEmploymentIndustry",
		"PProfileNationality",
		"PProfileOffBoardingReason",
		"PProfileRiskRiskCategory",
		"PPROverridenRiskCategory",
		"PPTaxIdentificationType",
		"ProblemCategory",
		"ProblemDefinitionCategory",
		"ProblemDefinitionPriority",
		"ProblemDefinitionUsageTypeEnum",
		"ProblemImpact",
		"ProblemPriority",
		"ProblemRelatedItemImpactLevel",
		"ProblemRelatedItemImpactType",
		"ProblemStatus",
		"ProblemSubCategory",
		"ProblemUrgency",
		"ProcessExceptionCategory",
		"ProcessExceptionPriority",
		"ProcessExceptionSeverity",
		"ProcessExceptionStatus",
		"Product2Family",
		"ProdRequestLineItemStatus",
		"ProductLineEnum",
		"ProductRequestStatus",
		"ProgressionCriteriaMet",
		"PScreeningStepResultCode",
		"PScreeningStepStatus",
		"PSSResultOverrideReason",
		"PSStepMatchedFieldList",
		"PSSummaryScreenedBy",
		"PSSummaryScreeningDecision",
		"PurchaserPlanAffiliation",
		"PurchaserPlanStatus",
		"PurchaserPlanType",
		"QuantityUnitOfMeasure",
		"QuestionOrigin",
		"QuickTextCategory",
		"QuickTextChannel",
		"QuoteStatus",
		"ReceivedDocumentDirection",
		"ReceivedDocumentOcrStatus",
		"ReceivedDocumentPriority",
		"ReceivedDocumentStatus",
		"RegAuthCategory",
		"RegulatoryBodyType",
		"ReopenReason",
		"RequestedCareCodeType",
		"RequestedDrugCodeType",
		"RequestedLevelOfCare",
		"RequesterType",
		"RequestingPractitionerLicense",
		"RequestingPractitionerSpecialty",
		"ResidenceStatusType",
		"RoleInTerritory",
		"ResourceAbsenceType",
		"ReturnOrderLineItemProcessPlan",
		"ReturnOrderLineItemReasonForRejection",
		"ReturnOrderLineItemReasonForReturn",
		"ReturnOrderLineItemRepaymentMethod",
		"ReturnOrderShipmentType",
		"ReturnOrderStatus",
		"SalesTeamRole",
		"Salutation",
		"SAppointmentGroupStatus",
		"ScorecardMetricCategory",
		"ScienceBasedTargetStatus",
		"SContributionSumCategory",
		"Scope3CrbnFtprntStage",
		"ServiceAppointmentStatus",
		"ServiceContractApprovalStatus",
		"ServicePlanTemplateStatus",
		"ServicingPractitionerLicense",
		"ServicingPractitionerSpecialty",
		"ServTerrMemRoleType",
		"ShiftStatus",
		"SocialContributionSumType",
		"SocialPostClassification",
		"SocialPostEngagementLevel",
		"SocialPostReviewedStatus",
		"SolutionStatus",
		"SourceBusinessRegion",
		"StatusReason",
		"StnryAssetCrbnFtprntStage",
		"StnryAstCrbnFtAllocStatus",
		"StnryAstCrbnFtDataGapSts",
		"StnryAstCrbnFtAllocStatus",
		"StnryAstCrbnFtDataGapSts",
		"StnryAstEvSrcStnryAstTyp",
		"StnryAssetWaterFtprntStage",
		"SupplierClassification",
		"SupplierEmssnRdctnCmtTypev",
		"SupplierReportingScope",
		"SupplierTier",
		"SustainabilityScorecardStatus",
		"TaskPriority",
		"TaskStatus",
		"TaskSubject",
		"TaskType",
		"TCDDetailType",
		"TCPriority",
		"TCStatus",
		"TCStatusReason",
		"TopicFailureReasonEnum",
		"TopicProcessStatusEnum",
		"TrackedCommunicationType",
		"TypesOfIntervention",
		"UnitOfMeasure",
		"UnitOfMeasureType",
		"VehicleAstCrbnFtprntStage",
		"VehicleType",
		"WasteFootprintStage",
		"WasteDisposalType",
		"WasteType",
		"WorkOrderLineItemPriority",
		"WorkOrderLineItemStatus",
		"WorkOrderPriority",
		"WorkOrderStatus",
		"WorkStepStatus",
		"WorkTypeDefApptType",
		"WorkTypeGroupAddInfo",
	}

	if (!isExcluded(standardValueSet) && exportAll) || isIncluded(standardValueSet) {
		query = append(query, ForceMetadataQueryElement{Name: []string{standardValueSet}, Members: standardValueSetNames})
	}

	metadataNames := []string{
		"AccountForecastSettings",
		"AccountingFieldMapping",
		"AccountingModelConfig",
		"AccountingSettings",
		"AccountIntelligenceSettings",
		"AccountRelationshipShareRule",
		"AccountSettings",
		"AcctMgrTargetSettings",
		"ActionableEventOrchDef",
		"ActionableEventTypeDef",
		"ActionableListDefinition",
		"ActionLauncherItemDef",
		"ActionLinkGroupTemplate",
		"ActionPlanTemplate",
		"ActionsSettings",
		"ActivationPlatform",
		"ActivitiesSettings",
		"ActnblListKeyPrfmIndDef",
		"AddressSettings",
		"AdvAccountForecastSet",
		"AdvAcctForecastDimSource",
		"AdvAcctForecastPeriodGroup",
		"Ai4mSettings",
		"AIApplication",
		"AIApplicationConfig",
		"AIReplyRecommendationsSettings",
		"AIScoringModelDefinition",
		"AIScoringModelDefVersion",
		"AIUsecaseDefinition",
		"AnalyticSnapshot",
		"AnalyticsSettings",
		"AnimationRule",
		"ApexClass",
		"ApexComponent",
		"ApexEmailNotifications",
		"ApexPage",
		"ApexSettings",
		"ApexTestSuite",
		"ApexTrigger",
		"AppAnalyticsSettings",
		"AppExperienceSettings",
		"ApplicationRecordTypeConfig",
		"ApplicationSubtypeDefinition",
		"AppMenu",
		"AppointmentAssignmentPolicy",
		"AppointmentSchedulingPolicy",
		"ApprovalProcess",
		"AssessmentConfiguration",
		"AssessmentQuestion",
		"AssessmentQuestionSet",
		"AssignmentRules",
		"AssistantContextItem",
		"AssistantDefinition",
		"AssistantSkillQuickAction",
		"AssistantSkillSobjectAction",
		"AssistantVersion",
		"AssociationEngineSettings",
		"Audience",
		"AuraDefinitionBundle",
		"AuthProvider",
		"AutomatedContactsSettings",
		"AutoResponseRules",
		"BatchCalcJobDefinition",
		"BatchProcessJobDefinition",
		"BenefitAction",
		"BlacklistedConsumer",
		"BldgEnrgyIntensityCnfg",
		"BlockchainSettings",
		"Bot",
		"BotBlock",
		"BotBlockVersion",
		"BotSettings",
		"BotTemplate",
		"BotVersion",
		"BranchManagementSettings",
		"BrandingSet",
		"BriefcaseDefinition",
		"BusinessHoursSettings",
		"BusinessProcess",
		"BusinessProcessGroup",
		"BusinessProcessTypeDefinition",
		"CallCenter",
		"CallCenterRoutingMap",
		"CallCoachingMediaProvider",
		"CampaignInfluenceModel",
		"CampaignSettings",
		"CanvasMetadata",
		"CareBenefitVerifySettings",
		"CareLimitType",
		"CareProviderAfflRoleConfig",
		"CareProviderSearchConfig",
		"CareRequestConfiguration",
		"CareSystemFieldMapping",
		"CaseSettings",
		"CaseSubjectParticle",
		"Certificate",
		"ChannelLayout",
		"ChannelObjectLinkingRule",
		"ChatterAnswersSettings",
		"ChatterEmailsMDSettings",
		"ChatterExtension",
		"ChatterSettings",
		"ClaimFinancialSettings",
		"ClaimMgmtFoundationEnabledSettings",
		"ClauseCatgConfiguration",
		"CleanDataService",
		"CMSConnectSource",
		"CodeBuilderSettings",
		"CollectionsDashboardSettings",
		"CommandAction",
		"CommerceSettings",
		"CommsServiceConsoleSettings",
		"CommunitiesSettings",
		"Community",
		"CommunityTemplateDefinition",
		"CommunityThemeDefinition",
		"CompactLayout",
		"CompanySettings",
		"ConnectedApp",
		"ConnectedAppSettings",
		"ContentAsset",
		"ContentSettings",
		"ContextDefinition",
		"ContractSettings",
		"ContractType",
		"ConversationalIntelligenceSettings",
		"ConversationChannelDefinition",
		"ConversationServiceIntegrationSettings",
		"ConversationVendorInfo",
		"CorsWhitelistOrigin",
		"CspTrustedSite",
		"CurrencySettings",
		"CustomAddressFieldSettings",
		"CustomApplication",
		"CustomApplicationComponent",
		"CustomerDataPlatformSettings",
		"CustomFeedFilter",
		"CustomField",
		"CustomHelpMenuSection",
		"CustomIndex",
		"CustomizablePropensityScoringSettings",
		"CustomLabels",
		"CustomMetadata",
		"CustomNotificationType",
		//"CustomObject",
		"CustomObjectTranslation",
		"CustomPageWebLink",
		"CustomPermission",
		"CustomSite",
		"CustomTab",
		//"CustomValue",
		//"Dashboard",
		"DashboardFolder",
		"DataCalcInsightTemplate",
		"DataCategoryGroup",
		"DataConnectorIngestApi",
		"DataConnectorS3",
		"DataDotComSettings",
		"DataImportManagementSettings",
		"DataKitObjectTemplate",
		"DataPackageKitDefinition",
		"DataPackageKitObject",
		"DataSource",
		"DataSourceBundleDefinition",
		"DataSourceObject",
		"DataSourceTenant",
		"DataSrcDataModelFieldMap",
		"DataStreamDefinition",
		"DataStreamTemplate",
		"DataWeaveResource",
		"DecisionMatrixDefinition",
		"DecisionMatrixDefinitionVersion",
		"DecisionTable",
		"DecisionTableDatasetLink",
		"DelegateGroup",
		"DeploymentSettings",
		"DevHubSettings",
		"DigitalExperience",
		"DigitalExperienceBundle",
		"DigitalExperienceConfig",
		"DisclosureDefinition",
		"DisclosureDefinitionVersion",
		"DisclosureType",
		"DiscoveryAIModel",
		"DiscoveryGoal",
		"DiscoverySettings",
		"DiscoveryStory",
		//"Document",
		"DocumentCategory",
		"DocumentCategoryDocumentType",
		"DocumentChecklistSettings",
		"DocumentFolder",
		"DocumentGenerationSetting",
		"DocumentType",
		"DuplicateRule",
		"DynamicFormsSettings",
		"EACSettings",
		"EclairGeoData",
		"EinsteinAgentSettings",
		"EinsteinAISettings",
		"EinsteinAssistantSettings",
		"EinsteinDealInsightsSettings",
		"EinsteinDocumentCaptureSettings",
		"EinsteinGptSettings",
		"EmailAdministrationSettings",
		"EmailFolder",
		"EmailIntegrationSettings",
		"EmailServicesFunction",
		//"EmailTemplate",
		"EmailTemplateFolder",
		"EmailTemplateSettings",
		"EmbeddedServiceBranding",
		"EmbeddedServiceConfig",
		"EmbeddedServiceFlowConfig",
		"EmbeddedServiceLiveAgent",
		"EmbeddedServiceMenuSettings",
		"EmployeeDataSyncProfile",
		"EmployeeFieldAccessSettings",
		//"EmployeeUserSettings",
		"EnhancedNotesSettings",
		"EntitlementProcess",
		"EntitlementSettings",
		"EntitlementTemplate",
		"EscalationRules",
		"ESignatureConfig",
		"ESignatureEnvelopeConfig",
		"EssentialsSettings",
		"EventLogObjectSettings",
		"EventSettings",
		"ExperienceBundle",
		"ExperienceBundleSettings",
		"ExperiencePropertyTypeBundle",
		"ExplainabilityActionDefinition",
		"ExplainabilityActionVersion",
		"ExplainabilityMsgTemplate",
		"ExpressionSetDefinition",
		"ExpressionSetDefinitionVersion",
		"ExpressionSetMessageToken",
		"ExpressionSetObjectAlias",
		"ExtDataTranFieldTemplate",
		"ExtDataTranObjectTemplate",
		"ExternalAIModel",
		"ExternalClientApplication",
		"ExternalClientAppSettings",
		"ExternalCredential",
		"ExternalDataConnector",
		"ExternalDataSource",
		"ExternalDataSrcDescriptor",
		"ExternalDataTranField",
		"ExternalDataTranObject",
		"ExternalDocStorageConfig",
		"ExternalServiceRegistration",
		"ExtlClntAppConfigurablePolicies",
		"ExtlClntAppGlobalOauthSettings",
		"ExtlClntAppMobileConfigurablePolicies",
		"ExtlClntAppMobileSettings",
		"ExtlClntAppNotificationSettings",
		"ExtlClntAppOauthConfigurablePolicies",
		"ExtlClntAppOauthSettings",
		"FeatureParameterBoolean",
		"FeatureParameterDate",
		"FeatureParameterInteger",
		"FieldRestrictionRule",
		"FieldServiceMobileExtension",
		"FieldServiceSettings",
		"FieldSet",
		"FieldSrcTrgtRelationship",
		"FilesConnectSettings",
		"FileUploadAndDownloadSecuritySettings",
		"FlexiPage",
		"Flow",
		"FlowCategory",
		"FlowDefinition",
		"FlowSettings",
		"FlowTest",
		"ForecastingFilter",
		"ForecastingFilterCondition",
		"ForecastingObjectListSettings",
		"ForecastingSettings",
		"ForecastingSourceDefinition",
		"ForecastingType",
		"ForecastingTypeSource",
		"FormulaSettings",
		"FuelType",
		"FuelTypeSustnUom",
		"FunctionReference",
		"FundraisingConfig",
		"GatewayProviderPaymentMethodType",
		"GenAiFunction",
		"GenAiPlanner",
		"GenAiPlugin",
		"GlobalValueSet",
		"GlobalValueSetTranslation",
		"GoogleAppsSettings",
		"Group",
		"HighVelocitySalesSettings",
		"HomePageComponent",
		"HomePageLayout",
		"Icon",
		"IdeasSettings",
		"IdentityProviderSettings",
		"IdentityVerificationProcDef",
		"IframeWhiteListUrlSettings",
		"InboundCertificate",
		"InboundNetworkConnection",
		"IncidentMgmtSettings",
		"IncludeEstTaxInQuoteCPQSettings",
		"IncludeEstTaxInQuoteSettings",
		"Index",
		"IndustriesAutomotiveSettings",
		"IndustriesContextSettings",
		"IndustriesEinsteinFeatureSettings",
		"IndustriesEventOrchSettings",
		"IndustriesFieldServiceSettings",
		"IndustriesGamificationSettings",
		"IndustriesLoyaltySettings",
		"IndustriesManufacturingSettings",
		"IndustriesPricingSettings",
		"IndustriesSettings",
		"IndustriesUnifiedPromotionsSettings",
		"InstalledPackage",
		"IntegrationProviderDef",
		"InterestTaggingSettings",
		"InternalDataConnector",
		"InventorySettings",
		"InvLatePymntRiskCalcSettings",
		"InvocableActionSettings",
		"IoTSettings",
		"IPAddressRange",
		"KeywordList",
		"KnowledgeGenerationSettings",
		"KnowledgeSettings",
		"LanguageSettings",
		"Layout",
		"LeadConfigSettings",
		"LeadConvertSettings",
		"LearningAchievementConfig",
		"Letterhead",
		"LicensingSettings",
		"LightningBolt",
		"LightningComponentBundle",
		"LightningExperienceSettings",
		"LightningExperienceTheme",
		"LightningMessageChannel",
		"LightningOnboardingConfig",
		"ListView",
		"LiveAgentSettings",
		"LiveChatAgentConfig",
		"LiveChatButton",
		"LiveChatDeployment",
		"LiveChatSensitiveDataRule",
		"LiveMessageSettings",
		"LocationUse",
		"LoyaltyProgramSetup",
		"MacroSettings",
		"MailMergeSettings",
		"ManagedContentType",
		"ManagedEventSubscription",
		"ManagedTopics",
		"MapsAndLocationSettings",
		"MarketingAppExtActivity",
		"MarketingAppExtension",
		"MarketSegmentDefinition",
		"MatchingRules",
		"MediaAdSalesSettings",
		"MeetingsSettings",
		"MessagingChannel",
		"MfgProgramTemplate",
		"MfgServiceConsoleSettings",
		"MilestoneType",
		"MktCalcInsightObjectDef",
		"MktDataTranObject",
		"MlDomain",
		"MobileApplicationDetail",
		"MobileSecurityAssignment",
		"MobileSecurityPolicy",
		"MobileSettings",
		"MobSecurityCertPinConfig",
		"ModerationRule",
		"MutingPermissionSet",
		"MyDomainDiscoverableLogin",
		"MyDomainSettings",
		"NamedCredential",
		"NameSettings",
		"NavigationMenu",
		"Network",
		"NetworkBranding",
		"NotificationsSettings",
		"NotificationTypeConfig",
		"OauthCustomScope",
		"OauthOidcSettings",
		"OauthTokenExchangeHandler",
		"ObjectHierarchyRelationship",
		"ObjectLinkingSettings",
		"ObjectSourceTargetMap",
		"OcrSampleDocument",
		"OcrTemplate",
		"OmniChannelPricingSettings",
		"OmniChannelSettings",
		"OmniDataTransform",
		"OmniExtTrackingDef",
		"OmniIntegrationProcedure",
		"OmniInteractionAccessConfig",
		"OmniInteractionConfig",
		"OmniScript",
		"OmniSupervisorConfig",
		"OmniTrackingGroup",
		"OmniUiCard",
		"OnlineSalesSettings",
		"OpportunityScoreSettings",
		"OpportunitySettings",
		"OrderManagementSettings",
		"OrderSettings",
		"OrgSettings",
		"OutboundNetworkConnection",
		"PardotEinsteinSettings",
		"PardotSettings",
		"ParticipantRole",
		"PartyDataModelSettings",
		"PathAssistant",
		"PathAssistantSettings",
		"PaymentGatewayProvider",
		"PaymentsManagementEnabledSettings",
		"PaymentsSettings",
		"PermissionSet",
		"PermissionSetGroup",
		"PermissionSetLicenseDefinition",
		"PersonAccountOwnerPowerUser",
		"PicklistSettings",
		//"PicklistValue",
		"PipelineInspMetricConfig",
		"PlatformCachePartition",
		"PlatformEventChannel",
		"PlatformEventChannelMember",
		"PlatformEventSettings",
		"PlatformEventSubscriberConfig",
		"PlatformSlackSettings",
		"PortalDelegablePermissionSet",
		"PortalsSettings",
		"PostTemplate",
		"PredictionBuilderSettings",
		"PresenceDeclineReason",
		"PresenceUserConfig",
		"PricingActionParameters",
		"PricingRecipe",
		"PrivacySettings",
		"ProcessFlowMigration",
		"ProductAttrDisplayConfig",
		"ProductAttributeSet",
		"ProductConfiguratorSettings",
		"ProductSettings",
		"ProductSpecificationRecType",
		"ProductSpecificationType",
		"Profile",
		"ProfilePasswordPolicy",
		"ProfileSessionSetting",
		"Prompt",
		"Queue",
		"QueueRoutingConfig",
		"QuickAction",
		"QuickTextSettings",
		"QuoteSettings",
		"RealTimeEventSettings",
		"RecAlrtDataSrcExpSetDef",
		"RecommendationBuilderSettings",
		"RecommendationStrategy",
		"RecordActionDeployment",
		"RecordAggregationDefinition",
		"RecordAlertCategory",
		"RecordAlertDataSource",
		"RecordAlertTemplate",
		"RecordPageSettings",
		"RecordType",
		"RedirectWhitelistUrl",
		"ReferencedDashboard",
		"ReferralMarketingSettings",
		"RegisteredExternalService",
		"RelatedRecordAssocCriteria",
		"RelationshipGraphDefinition",
		"RemoteSiteSetting",
		//"Report",
		"ReportFolder",
		"ReportType",
		"RestrictionRule",
		"RetailExecutionSettings",
		"RevenueManagementSettings",
		"Role",
		"SalesAgreementSettings",
		"SalesWorkQueueSettings",
		"SamlSsoConfig",
		"SandboxSettings",
		"SceGlobalModelOptOutSettings",
		"SchedulingObjective",
		"SchedulingRule",
		"SchemaSettings",
		"ScoreCategory",
		"SearchSettings",
		"SecuritySettings",
		"ServiceAISetupDefinition",
		"ServiceAISetupField",
		"ServiceChannel",
		"ServiceCloudVoiceSettings",
		"ServicePresenceStatus",
		"ServiceProcess",
		"ServiceSetupAssistantSettings",
		"SharingCriteriaRule",
		"SharingGuestRule",
		"SharingOwnerRule",
		"SharingReason",
		"SharingRules",
		"SharingSet",
		"SharingSettings",
		"SharingTerritoryRule",
		"SiteDotCom",
		"SiteSettings",
		"Skill",
		"SkillType",
		"SlackApp",
		"SocialCustomerServiceSettings",
		"SourceTrackingSettings",
		"StandardValue",
		//"StandardValueSet",
		"StandardValueSetTranslation",
		"StaticResource",
		"StnryAssetEnvSrcCnfg",
		"StreamingAppDataConnector",
		"SubscriptionManagementSettings",
		"SurveySettings",
		"SustainabilityUom",
		"SustnUomConversion",
		"SvcCatalogCategory",
		"SvcCatalogFilterCriteria",
		"SvcCatalogFulfillmentFlow",
		"SvcCatalogItemDef",
		"SynonymDictionary",
		"SystemNotificationSettings",
		"Territory",
		"Territory2",
		"Territory2Model",
		"Territory2Rule",
		"Territory2Settings",
		"Territory2Type",
		"TimelineObjectDefinition",
		"TimeSheetTemplate",
		//"TopicsForObjects",
		"TrailheadSettings",
		"TransactionSecurityPolicy",
		"Translations",
		"TrialOrgSettings",
		//"UIObjectRelationConfig",
		"UiPlugin",
		"UserAccessPolicy",
		"UserAuthCertificate",
		"UserCriteria",
		"UserEngagementSettings",
		"UserInterfaceSettings",
		"UserManagementSettings",
		"UserProfileSearchScope",
		"UserProvisioningConfig",
		"ValidationRule",
		"VehicleAssetEmssnSrcCnfg",
		"ViewDefinition",
		"VirtualVisitConfig",
		"VoiceSettings",
		"WarrantyLifecycleMgmtSettings",
		"WaveApplication",
		"WaveComponent",
		"WaveDashboard",
		"WaveDataflow",
		"WaveDataset",
		"WaveLens",
		"WaveRecipe",
		"WaveTemplateBundle",
		"WaveXmd",
		"Web3Settings",
		"WebLink",
		"WebStoreBundle",
		"WebStoreTemplate",
		"WebToXSettings",
		"WorkDotComSettings",
		"Workflow",
		"WorkflowAlert",
		"WorkflowFieldUpdate",
		"WorkflowFlowAction",
		"WorkflowKnowledgePublish",
		"WorkflowOutboundMessage",
		"WorkflowRule",
		"WorkflowSend",
		"WorkflowTask",
		"WorkforceEngagementSettings",
		"WorkSkillRouting",
	}

	// add support for only extracting certain objects
	if len(includeMetadataNames) > 0 {
		metadataNames = includeMetadataNames
	}

	for _, name := range metadataNames {
		if !isExcluded(name) {
			query = append(query, ForceMetadataQueryElement{Name: []string{name}, Members: []string{"*"}})
		}
	}

	if exportAll || isIncluded("EmailTemplate") {

		folders, err := force.GetAllFolders()
		if err != nil {
			err = fmt.Errorf("Could not get folders: %s", err.Error())
			ErrorAndExit(err.Error())
		}
		for foldersType, foldersName := range folders {
			if foldersType == "Email" {
				foldersType = "EmailTemplate"
			}
			members, err := force.GetMetadataInFolders(foldersType, foldersName)
			if err != nil {
				err = fmt.Errorf("Could not get metadata in folders: %s", err.Error())
				ErrorAndExit(err.Error())
			}

			if !isExcluded(string(foldersType)) {
				query = append(query, ForceMetadataQueryElement{Name: []string{string(foldersType)}, Members: members})
			}
		}
	}
	// fmt.Printf("Query: %s\n", query)

	if root == "" {
		root, err = config.GetSourceDir()
		if err != nil {
			fmt.Printf("Error obtaining root directory\n")
			ErrorAndExit(err.Error())
		}
	}
	files, problems, err := force.Metadata.Retrieve(query)
	if err != nil {
		fmt.Printf("Encountered and error with retrieve...\n")
		ErrorAndExit(err.Error())
	}
	if showWarnings {
		for _, problem := range problems {
			fmt.Fprintln(os.Stderr, problem)
		}
	}
	newline := []byte("")
	if addNewline {
		newline = []byte("\n")
	}
	for name, data := range files {
		file := filepath.Join(root, name)
		dir := filepath.Dir(file)
		if err := os.MkdirAll(dir, 0755); err != nil {
			ErrorAndExit(err.Error())
		}
		if err := ioutil.WriteFile(filepath.Join(root, name), append(data, newline...), 0644); err != nil {
			ErrorAndExit(err.Error())
		}
	}
	fmt.Printf("Exported to %s\n", root)
}

func isExcluded(name string) bool {
	index := sort.SearchStrings(excludeMetadataNames, name)

	return index < len(excludeMetadataNames) && excludeMetadataNames[index] == name
}

func isIncluded(name string) bool {
	index := sort.SearchStrings(includeMetadataNames, name)

	return index < len(includeMetadataNames) && includeMetadataNames[index] == name
}
